// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFC5Jc48cBUtmFcBBPGuJcr6eDjGCp9GU',
    appId: '1:54854737069:web:c2e33bc968811da7637a24',
    messagingSenderId: '54854737069',
    projectId: 'smartprep-450d8',
    authDomain: 'smartprep-450d8.firebaseapp.com',
    storageBucket: 'smartprep-450d8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_MGjBMx7vjC637u1DPvLSnJlaNSmUHck',
    appId: '1:54854737069:android:af99ff4a2d85ff93637a24',
    messagingSenderId: '54854737069',
    projectId: 'smartprep-450d8',
    storageBucket: 'smartprep-450d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcvGUF_BdU2v0DeVvfoU5Bg2_D6qp15Q4',
    appId: '1:54854737069:ios:814ff6652acfb594637a24',
    messagingSenderId: '54854737069',
    projectId: 'smartprep-450d8',
    storageBucket: 'smartprep-450d8.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcvGUF_BdU2v0DeVvfoU5Bg2_D6qp15Q4',
    appId: '1:54854737069:ios:814ff6652acfb594637a24',
    messagingSenderId: '54854737069',
    projectId: 'smartprep-450d8',
    storageBucket: 'smartprep-450d8.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFC5Jc48cBUtmFcBBPGuJcr6eDjGCp9GU',
    appId: '1:54854737069:web:f44c226cf8c792d4637a24',
    messagingSenderId: '54854737069',
    projectId: 'smartprep-450d8',
    authDomain: 'smartprep-450d8.firebaseapp.com',
    storageBucket: 'smartprep-450d8.firebasestorage.app',
  );
}
